spring:
  jpa:
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    default-property-inclusion: non_null

  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/init.sql



  profiles:
    active: h2

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
  context_path: /api/v1

springdoc:
  swagger-ui:
    url: /clients.yaml

logging:
  level:
    root: WARN
    ru.ustinov.clients: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: user
    password: password

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    # ImMemory
    url: jdbc:h2:mem:clients
    #   tcp: jdbc:h2:tcp://localhost:9092/mem:clients
    h2.console.enabled: true


